// Converts snarkjs Groth16 artifacts (verification_key.json, proof.json,
// public.json) into Rust source for the Soroban BN254 verifier contract.
//
// Soroban BN254 serialization (Ethereum-compatible, uncompressed):
//   G1 (64 bytes):  be(X) || be(Y)
//   G2 (128 bytes): be(X) || be(Y), where each Fp2 element is be(c1) || be(c0)
//                   (imaginary component FIRST, then real component)
//
// snarkjs stores Fp2 coordinates as [c0, c1], so we must swap to [c1, c0].
//
// Usage:  node gen_verifier_data.js
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const OUT_DIR = path.join(__dirname, "contracts", "meteredverifier", "src");
const ESCROW_FIXTURE = path.join(
  ROOT,
  "..",
  "contract",
  "contracts",
  "slate-escrow",
  "src",
  "fixture.rs"
);

const vk = JSON.parse(
  fs.readFileSync(path.join(ROOT, "setttlement_verification_key.json"), "utf8")
);
const proof = JSON.parse(fs.readFileSync(path.join(ROOT, "proof.json"), "utf8"));
const pub = JSON.parse(fs.readFileSync(path.join(ROOT, "public.json"), "utf8"));

// 32-byte big-endian hex (no 0x) for a decimal field-element string.
function be32(dec) {
  const hex = BigInt(dec).toString(16);
  if (hex.length > 64) throw new Error(`value too large: ${dec}`);
  return hex.padStart(64, "0");
}

// Render a hex string as a Rust byte-array literal body: "0xaa, 0xbb, ..."
function rustBytes(hex) {
  const out = [];
  for (let i = 0; i < hex.length; i += 2) out.push(`0x${hex.slice(i, i + 2)}`);
  // 16 bytes per line for readability
  const lines = [];
  for (let i = 0; i < out.length; i += 16) {
    lines.push("        " + out.slice(i, i + 16).join(", ") + ",");
  }
  return lines.join("\n");
}

// G1 point [x, y, z] -> 64-byte hex (affine, z must be 1).
function g1Hex(p) {
  return be32(p[0]) + be32(p[1]);
}

// G2 point [[x_c0, x_c1], [y_c0, y_c1], z] -> 128-byte hex with c1||c0 order.
function g2Hex(p) {
  const x = be32(p[0][1]) + be32(p[0][0]); // be(x_c1) || be(x_c0)
  const y = be32(p[1][1]) + be32(p[1][0]); // be(y_c1) || be(y_c0)
  return x + y;
}

function g1Fn(name, p) {
  return `pub fn ${name}(env: &Env) -> Bn254G1Affine {
    Bn254G1Affine::from_bytes(BytesN::from_array(
        env,
        &[
${rustBytes(g1Hex(p))}
        ],
    ))
}
`;
}

function g2Fn(name, p) {
  return `pub fn ${name}(env: &Env) -> Bn254G2Affine {
    Bn254G2Affine::from_bytes(BytesN::from_array(
        env,
        &[
${rustBytes(g2Hex(p))}
        ],
    ))
}
`;
}

// ---------------- vk.rs ----------------
let icFn = `pub fn ic(env: &Env) -> Vec<Bn254G1Affine> {
    vec![
        env,
`;
for (const p of vk.IC) {
  icFn += `        Bn254G1Affine::from_bytes(BytesN::from_array(
            env,
            &[
${rustBytes(g1Hex(p)).replace(/^ {8}/gm, "                ")}
            ],
        )),
`;
}
icFn += `    ]
}
`;

const vkRs = `// AUTO-GENERATED by gen_verifier_data.js. Do not edit by hand.
// Source: setttlement_verification_key.json (Groth16 / BN254 / nPublic=${vk.nPublic}).
#![allow(clippy::all)]
use soroban_sdk::{
    crypto::bn254::{Bn254G1Affine, Bn254G2Affine},
    vec, BytesN, Env, Vec,
};

pub const N_PUBLIC: u32 = ${vk.nPublic};

${g1Fn("alpha_g1", vk.vk_alpha_1)}
${g2Fn("beta_g2", vk.vk_beta_2)}
${g2Fn("gamma_g2", vk.vk_gamma_2)}
${g2Fn("delta_g2", vk.vk_delta_2)}
${icFn}`;

fs.writeFileSync(path.join(OUT_DIR, "vk.rs"), vkRs);

// ---------------- fixture.rs (test data) ----------------
let pubArr = `pub fn public_signals(env: &Env) -> Vec<U256> {
    vec![
        env,
`;
for (const s of pub) {
  pubArr += `        U256::from_be_bytes(env, &Bytes::from_array(env, &[
${rustBytes(be32(s)).replace(/^ {8}/gm, "            ")}
        ])),
`;
}
pubArr += `    ]
}
`;

const fixtureRs = `// AUTO-GENERATED by gen_verifier_data.js. Do not edit by hand.
// A real proof produced by the snarkjs pipeline, for use in tests.
#![allow(clippy::all)]
use soroban_sdk::{vec, Bytes, BytesN, Env, U256, Vec};

pub fn proof_a(env: &Env) -> BytesN<64> {
    BytesN::from_array(
        env,
        &[
${rustBytes(g1Hex(proof.pi_a))}
        ],
    )
}

pub fn proof_b(env: &Env) -> BytesN<128> {
    BytesN::from_array(
        env,
        &[
${rustBytes(g2Hex(proof.pi_b))}
        ],
    )
}

pub fn proof_c(env: &Env) -> BytesN<64> {
    BytesN::from_array(
        env,
        &[
${rustBytes(g1Hex(proof.pi_c))}
        ],
    )
}

${pubArr}`;

fs.writeFileSync(path.join(OUT_DIR, "fixture.rs"), fixtureRs);
fs.writeFileSync(ESCROW_FIXTURE, fixtureRs);

console.log("Wrote:");
console.log("  " + path.join(OUT_DIR, "vk.rs"));
console.log("  " + path.join(OUT_DIR, "fixture.rs"));
console.log("  " + ESCROW_FIXTURE);
