#!/usr/bin/env node
/**
 * Generate Soroban contract artifacts from snarkjs ceremony outputs:
 *   - meteredverifier/src/vk.rs
 *   - meteredverifier/src/fixture.rs
 *   - slate-escrow/src/fixture.rs
 *   - slate-agent-registry/src/fixture.rs
 *
 * Point encoding matches packages/proving-setup/src/serialize.ts:
 *   G1: be(X) || be(Y)
 *   G2: be(X.c1) || be(X.c0) || be(Y.c1) || be(Y.c0)
 */
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

function parseArgs(argv) {
  const opts = {
    vkey: "settlement_verification_key.json",
    proof: "artifacts/proof.json",
    public: "artifacts/public.json",
    outDir: path.join("..", "onchain-setup", "soroban", "contracts"),
  };
  for (let i = 2; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === "--vkey") opts.vkey = argv[++i];
    else if (arg === "--proof") opts.proof = argv[++i];
    else if (arg === "--public") opts.public = argv[++i];
    else if (arg === "--out-dir") opts.outDir = argv[++i];
    else {
      console.error(`unknown argument: ${arg}`);
      process.exit(1);
    }
  }
  return opts;
}

function toBigInt(value) {
  return BigInt(value);
}

function fieldToBytes32(value) {
  let v = toBigInt(value);
  if (v < 0n) throw new Error(`negative field element: ${value}`);
  const out = Buffer.alloc(32);
  for (let i = 31; i >= 0; i--) {
    out[i] = Number(v & 0xffn);
    v >>= 8n;
  }
  if (v !== 0n) throw new Error(`field element does not fit in 32 bytes: ${value}`);
  return out;
}

function serializeG1(point, label) {
  if (!Array.isArray(point) || point.length < 2) {
    throw new Error(`${label}: expected G1 point [x, y, z]`);
  }
  const z = point[2] ?? "1";
  if (toBigInt(z) !== 1n) {
    throw new Error(`${label}: expected affine G1 point (z = 1)`);
  }
  return Buffer.concat([fieldToBytes32(point[0]), fieldToBytes32(point[1])]);
}

function serializeG2(point, label) {
  if (!Array.isArray(point) || point.length < 2) {
    throw new Error(`${label}: expected G2 point`);
  }
  const [x, y] = point;
  if (!Array.isArray(x) || !Array.isArray(y) || x.length < 2 || y.length < 2) {
    throw new Error(`${label}: malformed G2 Fp2 coordinates`);
  }
  const z = point[2];
  if (z !== undefined) {
    if (toBigInt(z[0]) !== 1n || toBigInt(z[1]) !== 0n) {
      throw new Error(`${label}: expected affine G2 point`);
    }
  }
  const out = Buffer.alloc(128);
  out.set(fieldToBytes32(x[1]), 0);
  out.set(fieldToBytes32(x[0]), 32);
  out.set(fieldToBytes32(y[1]), 64);
  out.set(fieldToBytes32(y[0]), 96);
  return out;
}

function formatByteArray(bytes, indent = "        ") {
  const lines = [];
  for (let i = 0; i < bytes.length; i += 16) {
    const chunk = bytes.subarray(i, Math.min(i + 16, bytes.length));
    const hex = [...chunk].map((b) => `0x${b.toString(16).padStart(2, "0")}`).join(", ");
    const suffix = i + 16 < bytes.length ? "," : "";
    lines.push(`${indent}${hex}${suffix}`);
  }
  return lines.join("\n");
}

function bytesLiteral(bytes, indent = "        ") {
  return `&[\n${formatByteArray(bytes, indent)}\n    ]`;
}

function generateVkRs(vkey) {
  const nPublic = vkey.nPublic;
  const alpha = serializeG1(vkey.vk_alpha_1, "vk_alpha_1");
  const beta = serializeG2(vkey.vk_beta_2, "vk_beta_2");
  const gamma = serializeG2(vkey.vk_gamma_2, "vk_gamma_2");
  const delta = serializeG2(vkey.vk_delta_2, "vk_delta_2");

  const icEntries = vkey.IC.map((point, index) => {
    const bytes = serializeG1(point, `IC[${index}]`);
    return `        Bn254G1Affine::from_bytes(BytesN::from_array(
            env,
            ${bytesLiteral(bytes, "            ")}
        ))`;
  });

  return `// AUTO-GENERATED by gen_verifier_data.js. Do not edit by hand.
// Source: settlement_verification_key.json (Groth16 / BN254 / nPublic=${nPublic}).
#![allow(clippy::all)]
use soroban_sdk::{
    crypto::bn254::{Bn254G1Affine, Bn254G2Affine},
    vec, BytesN, Env, Vec,
};

pub const N_PUBLIC: u32 = ${nPublic};

pub fn alpha_g1(env: &Env) -> Bn254G1Affine {
    Bn254G1Affine::from_bytes(BytesN::from_array(
        env,
        ${bytesLiteral(alpha)}
    ))
}

pub fn beta_g2(env: &Env) -> Bn254G2Affine {
    Bn254G2Affine::from_bytes(BytesN::from_array(
        env,
        ${bytesLiteral(beta)}
    ))
}

pub fn gamma_g2(env: &Env) -> Bn254G2Affine {
    Bn254G2Affine::from_bytes(BytesN::from_array(
        env,
        ${bytesLiteral(gamma)}
    ))
}

pub fn delta_g2(env: &Env) -> Bn254G2Affine {
    Bn254G2Affine::from_bytes(BytesN::from_array(
        env,
        ${bytesLiteral(delta)}
    ))
}

pub fn ic(env: &Env) -> Vec<Bn254G1Affine> {
    vec![
        env,
${icEntries.join(",\n")}
    ]
}
`;
}

function generateFixtureRs(proof, publicSignals) {
  const proofA = serializeG1(proof.pi_a, "pi_a");
  const proofB = serializeG2(proof.pi_b, "pi_b");
  const proofC = serializeG1(proof.pi_c, "pi_c");

  const signalEntries = publicSignals.map((signal) => {
    const bytes = fieldToBytes32(signal);
    const hexLines = formatByteArray(bytes, "            ");
    return `        U256::from_be_bytes(
            env,
            &Bytes::from_array(
                env,
                &[
${hexLines},
                ],
            ),
        )`;
  });

  return `// AUTO-GENERATED by gen_verifier_data.js. Do not edit by hand.
// A real proof produced by the snarkjs pipeline, for use in tests.
#![allow(clippy::all)]
use soroban_sdk::{vec, Bytes, BytesN, Env, Vec, U256};

pub fn proof_a(env: &Env) -> BytesN<64> {
    BytesN::from_array(
        env,
        ${bytesLiteral(proofA, "        ")}
    )
}

pub fn proof_b(env: &Env) -> BytesN<128> {
    BytesN::from_array(
        env,
        ${bytesLiteral(proofB, "        ")}
    )
}

pub fn proof_c(env: &Env) -> BytesN<64> {
    BytesN::from_array(
        env,
        ${bytesLiteral(proofC, "        ")}
    )
}

pub fn public_signals(env: &Env) -> Vec<U256> {
    vec![
        env,
${signalEntries.join(",\n")}
    ]
}
`;
}

function main() {
  const opts = parseArgs(process.argv);
  const vkey = JSON.parse(readFileSync(opts.vkey, "utf8"));
  const proof = JSON.parse(readFileSync(opts.proof, "utf8"));
  const publicSignals = JSON.parse(readFileSync(opts.public, "utf8"));

  if (vkey.protocol !== "groth16" || vkey.curve !== "bn128") {
    throw new Error(`expected groth16/bn128 vkey, got ${vkey.protocol}/${vkey.curve}`);
  }
  if (!Array.isArray(publicSignals)) {
    throw new Error("public.json must be a JSON array");
  }
  if (publicSignals.length !== vkey.nPublic) {
    throw new Error(
      `public signal count ${publicSignals.length} != vkey.nPublic ${vkey.nPublic}`,
    );
  }

  const vkRs = generateVkRs(vkey);
  const fixtureRs = generateFixtureRs(proof, publicSignals);

  const targets = [
    path.join(opts.outDir, "meteredverifier", "src", "vk.rs"),
    path.join(opts.outDir, "meteredverifier", "src", "fixture.rs"),
    path.join(opts.outDir, "slate-escrow", "src", "fixture.rs"),
    path.join(opts.outDir, "slate-agent-registry", "src", "fixture.rs"),
  ];

  writeFileSync(targets[0], vkRs);
  for (const target of targets.slice(1)) {
    writeFileSync(target, fixtureRs);
  }

  console.log("wrote:");
  for (const target of targets) {
    console.log(`  ${target}`);
  }
}

main();
